version: '3'
services:
  impact-api:
    build:
      context: ./impact-api
    ports:
      - "3443:3443"
    networks:
      - impactnetwork

  impact-ui:
    build:
      context: ./impact-ui
    links:
      - impact-api
    ports:
      - "3000:3000"
    networks:
      - impactnetwork

volumes:
  mongodata:

networks:
  impactnetwork:
    driver: bridge
