version: '3'
services:
  impact-api:
    env_file:
      - ./impact-api/.env.development
    environment:
      API_IP: ${API_IP}
      API_PORT: ${API_PORT}
    build:
      context: ./impact-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./impact-api:/usr/src/app
    ports:
      - "3443:3443"
    networks:
      - impactnetwork

  impact-ui:
    env_file:
      - ./impact-ui/.env.development
    environment:
      CLIENT_IP: ${CLIENT_IP}
      CLIENT_PORT: ${CLIENT_PORT}
      API_IP: ${API_IP}
      API_PORT: ${API_PORT}
    build:
      context: ./impact-ui
      dockerfile: Dockerfile.dev
    links:
      - impact-api
    volumes:
      - ./impact-ui:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - impactnetwork

volumes:
  mongodata:

networks:
  impactnetwork:
    driver: bridge
