version: '3'
services:
  impact-api:
    restart: unless-stopped
    env_file:
      - ./.env.base.prod
      - ./impact-api/.env
    environment:
      PRODUCTION: 'true'

  impact-ui:
    restart: unless-stopped
    env_file:
      - ./.env.base.prod
      - ./impact-ui/.env
    environment:
      PRODUCTION: 'true'
